/* SQL para crear la tabla en Supabase */

create table transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  description text not null,
  amount numeric not null,
  type text check (type in ('income', 'expense')) not null
);

/* Políticas de seguridad (RLS) opcionales pero recomendadas si usas Auth */
/* Por ahora, si es para uso personal simple sin auth en frontend, asegúrate de deshabilitar RLS o crear políticas públicas */
